org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=C:/Program Files/Java/jdk-21

minecraft_version=1.21.1
neo_version=21.1.242
mod_id=typemoonaddon
mod_name=Type Moon Addon
mod_version=1.0.0
mod_group_id=io.github.typemoonaddon

type_moon_world_jar=../build/libs/typemoonworld-api-3.6.0.jar
terrablender_jar=C:/Users/21844/Desktop/动画/libs/runtime/TerraBlender-neoforge-1.21.1-4.1.0.8.jar
