pluginManagement {
    repositories {
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases/'
        }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases/'
        }
        maven {
            name = 'Minecraft Libraries'
            url = 'https://libraries.minecraft.net/'
        }
        mavenCentral()
    }
}

rootProject.name = 'typemoonaddon'
